# Generated by Django 3.2.13 on 2022-06-23 15:28

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
                ('oras', models.CharField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30)),
                ('gen', models.CharField(choices=[('Bărbaţi', 'Bărbaţi'), ('Femei', 'Femei'), ('Ambele', 'Ambele')], max_length=10)),
                ('de_la', models.DateTimeField(auto_now_add=True)),
                ('pana_la', models.DateTimeField(auto_now_add=True)),
                ('sporturi', models.CharField(choices=[('Toate', 'Toate'), ('Handbal', 'Handbal'), ('Fotbal', 'Fotbal'), ('Tenis de camp', 'Tenis de camp')], default='', max_length=15)),
                ('dificultate', models.CharField(choices=[('Toate', 'Toate'), ('Incepator', 'Incepator'), ('Intermediar', 'Intermediar'), ('Avansat', 'Avansat')], max_length=20)),
                ('descriere', models.TextField(max_length=800)),
                ('creat_in', models.DateTimeField(auto_now_add=True)),
                ('actualizat_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=60)),
                ('oras', models.CharField(max_length=20)),
                ('adresa', models.CharField(max_length=30)),
                ('descriere', models.TextField(max_length=1000)),
                ('creat_in', models.DateTimeField(auto_now_add=True)),
                ('actualizat_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
                ('prenume', models.CharField(max_length=20)),
                ('porecla', models.CharField(blank=True, max_length=20, null=True)),
                ('varsta', models.IntegerField()),
                ('oras', models.TextField(max_length=30)),
                ('descriere', models.TextField(blank=True, max_length=1000, null=True)),
                ('gen', models.CharField(choices=[('man', 'Bărbaţi'), ('women', 'Femei')], max_length=10)),
                ('poza', models.ImageField(blank=True, null=True, upload_to='static/playerPicture/')),
                ('creat_in', models.DateTimeField(auto_now_add=True)),
                ('actualizat_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('locatie', models.CharField(blank=True, max_length=30, null=True)),
                ('oras', models.CharField(max_length=30)),
                ('descriere', models.TextField(max_length=1000)),
                ('numar_minim_de_jucatori', models.IntegerField()),
                ('numar_maxim_de_jucatori', models.IntegerField()),
                ('gen', models.CharField(choices=[('man', 'Bărbaţi'), ('women', 'Femei')], default='', max_length=10)),
                ('creat_in', models.DateTimeField(auto_now_add=True)),
                ('actualizat_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtendCreateView',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nume', models.CharField(max_length=15)),
                ('prenume', models.CharField(max_length=15)),
                ('numar_telefon', models.CharField(max_length=15)),
                ('oras', models.CharField(max_length=15)),
                ('gen', models.CharField(choices=[('man', 'Bărbaţi'), ('women', 'Femei')], max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SportLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.location')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.sport')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.sport')),
            ],
        ),
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.location')),
            ],
        ),
    ]
