# Generated by Django 4.0.4 on 2022-05-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='prenume',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='prenume',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='prenume',
            new_name='nume',
        ),
    ]
