# Generated by Django 3.2.13 on 2022-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=50)),
                ('descriere', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/img/carousel_home')),
            ],
        ),
        migrations.CreateModel(
            name='FirstPageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=200)),
                ('continut', models.TextField(max_length=10000)),
                ('img', models.ImageField(upload_to='static/img/first_page_article')),
            ],
        ),
        migrations.CreateModel(
            name='FirstPageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link_address', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='static/img/first_page_article')),
            ],
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='UploadImage',
        ),
        migrations.AlterField(
            model_name='event',
            name='nume',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='oras',
            field=models.TextField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='adresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='nume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='oras',
            field=models.TextField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='oras',
            field=models.TextField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sport',
            name='oras',
            field=models.TextField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30),
        ),
    ]
