# Generated by Django 3.2.13 on 2022-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220703_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselContent',
        ),
        migrations.DeleteModel(
            name='FirstPageArticle',
        ),
        migrations.DeleteModel(
            name='FirstPageCard',
        ),
        migrations.AlterField(
            model_name='sport',
            name='nume',
            field=models.CharField(max_length=25),
        ),
    ]
