# Generated by Django 4.0.4 on 2022-06-01 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_rename_last_name_event_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtend',
            new_name='UserExtendCreateView',
        ),
        migrations.AlterField(
            model_name='sport',
            name='numar_maxim_de_jucatori',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='numar_minim_de_jucatori',
            field=models.IntegerField(),
        ),
    ]
