# Generated by Django 4.0.4 on 2022-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_event_oras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='oras',
            field=models.CharField(choices=[('SIBIU', 'SIBIU'), ('BRASOV', 'BRASOV'), ('CLUJ-NAPOCA', 'CLUJ-NAPOCA')], max_length=30),
        ),
    ]
